name: CD

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Remove old images if exist
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/student-performance-prediction:latest
          IMAGE_ID=$(docker images -q $IMAGE_NAME)
          if [ -n "$IMAGE_ID" ]; then
            echo "Removing old image $IMAGE_ID"
            docker rmi -f $IMAGE_ID
          else
            echo "No old image found"
          fi

      - name: Pull latest image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/student-performance-prediction:latest
          docker pull $IMAGE_NAME

      - name: Stop and remove old container
        run: |
          docker ps -q --filter "name=student-performance-prediction" | grep -q . && \
          docker stop student-performance-prediction && \
          docker rm student-performance-prediction || echo "No old container"

      - name: Run new container
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/student-performance-prediction:latest
          docker run -d --name student-performance-prediction -p 8000:8000 $IMAGE_NAME
